### ISSUE TITLE
AttributeError: module 'distutils' has no attribute 'spawn'

### ISSUE THREAD

**Issue by samedii** [shin-/dockerpy-creds#14]
```
Traceback (most recent call last):
  File "/home/richard/.pyenv/versions/3.8.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/richard/.pyenv/versions/3.8.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/richard/Documents/trafikverket-wire-damage-generation/.venv/lib/python3.8/site-packages/wandb/__main__.py", line 1, in <module>
    from wandb.cli import cli
  File "/home/richard/Documents/trafikverket-wire-damage-generation/.venv/lib/python3.8/site-packages/wandb/cli/cli.py", line 1281, in <module>
    default=find_executable("nvidia-docker") is not None,
  File "/home/richard/Documents/trafikverket-wire-damage-generation/.venv/lib/python3.8/site-packages/dockerpycreds/utils.py", line 12, in find_executable
    return distutils.spawn.find_executable(executable, path)
AttributeError: module 'distutils' has no attribute 'spawn'
```

**Comment by molule** [comment]
hi
I meet the same issue recently, could you please share the solution?

**Comment by Kait0** [comment]
```
Traceback (most recent call last):                                                                                                                                           
  File "/mnt/miniconda3/envs/2_rl/lib/python3.8/runpy.py", line 194, in _run_module_as_main                                                                                  
    return _run_code(code, main_globals, None,                                                                                                                               
  File "/mnt/miniconda3/envs/2_rl/lib/python3.8/runpy.py", line 87, in _run_code                                                                                             
    exec(code, run_globals)                                                                                                                                                  
  File "/mnt/miniconda3/envs/2_rl/lib/python3.8/site-packages/wandb/__main__.py", line 1, in <module>                                                                        
    from wandb.cli import cli                                                                                                                                                
  File "/mnt/miniconda3/envs/2_rl/lib/python3.8/site-packages/wandb/cli/cli.py", line 2061, in <module>                                                                      
    default=find_executable("nvidia-docker") is not None,                                                                                                                    
  File "/mnt/miniconda3/envs/2_rl/lib/python3.8/site-packages/dockerpycreds/utils.py", line 12, in find_executable                                                           
    return distutils.spawn.find_executable(executable, path)                                                                                                                 
AttributeError: module 'distutils' has no attribute 'spawn'
```

I encountered the same issue.
